version: '3.8'

services:
  bot:
    build: .
    container_name: kinobot_bot
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      - .session-data:/app/session_name.session
    command: python bot/main.py

# Optional: Local Postgres database
#  db:
#    image: postgres:15
#    container_name: kinobot_db
#    restart: always
#    environment:
#      POSTGRES_USER: myuser
#      POSTGRES_PASSWORD: mypassword
#      POSTGRES_DB: mydb
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
